services:
  go-api:
    build: ./go-pages-api
    ports:
      - "8080:8080"
    volumes:
      - ./go-pages-api/src:/app
    env_file:
      - .env

  reader-frontend:
    build: ./manga-reader-frontend
    volumes:
      - ./manga-reader-frontend:/app:delegated
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true

volumes:
  node_modules: