services:
  nignx:
    image: "nginx"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
    - "4000:4000"

  go-api:
    build: ./go-pages-api
    depends_on:
      - redis
    ports:
      - "8083:8080"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./go-pages-api/src:/app
    env_file:
      - .env

  reader-frontend:
    build: 
      context: ./reader-frontend
      target: prod
    volumes:
      - ./reader-frontend:/app:delegated
      - /app/node_modules
    env_file:
      - .env
    ports:
      - "3000:3000"
    environment:
       - CHOKIDAR_USEPOLLING=true
  redis:
    image: redis:alpine
    container_name: reader-redis
    ports:
      - "6380:6379"
    command: ["redis-server", "--maxmemory", "100mb", "--maxmemory-policy", "allkeys-lru"]
    volumes:
      - redis-data:/data
volumes:
  node_modules:
  redis-data: