import type { manwhaData } from "../types/types";
class manwhaWrapper {
    getManwhas(): Promise<manwhaData[]> {
        return new Promise((resolve) =>{
                resolve([{name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"},
                    {name:"Mangatitle 1235 in another worl..",
                    author:"Artsist drawer",
                    chapters:112,
                    coverURL:"https://placehold.co/96x137"}
            ]);
        });
    }
}

export const manwhaAPI = new manwhaWrapper();